default_agent: csai_agent
agents:
  csai_agent:
    name: csai_agent
    language: python
    node_version: '20'
    entrypoint: /Users/saurabhbhardwaj/Documents/Personal_Projects/ai_support_agent/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/saurabhbhardwaj/Documents/Personal_Projects/ai_support_agent
    aws:
      execution_role: arn:aws:iam::314182259346:role/csai-runtime-role
      execution_role_auto_create: false
      account: '314182259346'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: csai-deploy-314182259346
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: csai_agent-D414VsAXhF
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:314182259346:runtime/csai_agent-D414VsAXhF
      agent_session_id: c5c130aa-4597-47d5-920a-ec967abb4c4f
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
